spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: user
    password: secret
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com